bedrockstone_v2/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.generic import RedirectView
from django.views import i18n
from bedrockstone_v2 import settings
from web import views
from web.admin import admin_site

admin.autodiscover()


urlpatterns = i18n_patterns(url(r'^$', views.index, name='index'),
                       url(r'^shipping/$', views.shipping, name='shipping'),
                       url(r'^locations/(?P<name>.+)/$', views.location, name='locations'),
                       url(r'^admin/', include(admin_site.urls), name="bedrock"),
                       url(r'^products/$', views.Products.as_view(), name='products'),
                       url(r'^products/(.+)/$', views.CategoryDetail.as_view(), name='category'),
                       url(r'^product/(.+)$', views.ProductDetail.as_view(), name="productDetail"),
                       url(r'^about/$', views.aboutus, name='about'),
                       url(r'^contact/$', views.ContactUs.as_view(), name='contact'),
                       url(r'^jobs/$', views.Jobs.as_view(), name='jobs'),
                       url(r'^jobs/(.+)/$', views.JobDetail.as_view(), name='job'),
                       url(r'^showcase/$', views.VirtualShowcase.as_view(), name='showcase'),
                       url(r'^showcase/(.+)/$', views.Project.as_view(), name='project_type'),
                       url(r'^resources/coverage/$', views.coverage, name='coverage'),
                       url(r'^salesInquiry/', views.salesInquiry, name="salesInquiry"),
                       url(r'^thankyou/', views.thankyou, name="thankyou"),
                       url(r'^specials/$', views.specials, name='specials'),\
                       url(r'^(.+)/', views.Content.as_view(), name='content'),
                       
                       )


urlpatterns += url(r'^setlang/', include('django.conf.urls.i18n')),

web/models.py
import os

from django.db import models
from easy_thumbnails.files import get_thumbnailer
from image_cropping import ImageRatioField
import time


def upload_image(self, filename):
    result = "%s/%s_%s%s" % (type(self).__name__.lower(),
                             self.name.lower().replace(' ', '_'),
                             time.time(),
                             os.path.splitext(filename)[-1])

    return result


class SortableNamedModel(models.Model):
    name = models.CharField(max_length=100, help_text='The name for this item')
    long_description = models.TextField(null=True, blank=True,
                                        help_text='Description text used when this item is displayed on a full page')
    short_description = models.TextField(null=True, blank=True,
                                         help_text='Description text used when this item is shown in a list. '
                                                   'It will also be shown in bold format in front of the '
                                                   'long description on full page displays')
    slug = models.CharField(null=True, blank = True, max_length=100,
                            help_text='This field is used for links, it should usually be the name with spaces replaced'
                                      ' by an underscore')
    sort_order = models.IntegerField(default=500, help_text='The order in which this item will show on list pages')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['sort_order']
        abstract = True


class ImageTagModel(object):

    def image_tag(self):
        return "<img src='{0}' style='width:40px' />".format(
            get_thumbnailer(self.image).get_thumbnail({
                'size': (430, 360),
                'box': self.cropped, 'crop': True,
                'detail': True, }).url
        )
    image_tag.short_description = ''
    image_tag.allow_tags = True


class ModelWithPicture(SortableNamedModel, ImageTagModel):
    image = models.ImageField(null=True, upload_to=upload_image, default='product/no_image.jpeg',
                              help_text='The image to show for this item')
    cropped = ImageRatioField('image', '400x300')

    class Meta:
        abstract = True
        ordering = ['sort_order']


class Category(ModelWithPicture):
    homepage_position = models.IntegerField(null=True, blank=True,
                                            help_text="The order this shows on the home page. If no value is specified"
                                                      "the item will not show on the home page.")
    parent = models.ForeignKey("self", null = True, blank=True, help_text="Parent category", related_name="children")                                                      

    class Meta:
        verbose_name_plural = 'Categories'


class Product(ModelWithPicture):
    category = models.ForeignKey(Category)
    sold_out = models.NullBooleanField(null = True, default = False, 
    help_text="Display a Sold Out Image over the product image")
    vender_id = models.CharField(null = True, blank = True, max_length = 15, default = None, help_text = 'Quickbooks product id')
    retail_price = models.DecimalField(null = True, blank = True, decimal_places=2, max_digits = 15,
     default = None, help_text='Price to show on website.')
    more_images_text = models.CharField(null = True, blank = True, max_length = 45, default = "More Images", 
        help_text="Text to show above extra product images")


class ProductImage(models.Model, ImageTagModel):
    
    image = models.ImageField(null=True, upload_to="ProductImages/%Y/%m/%d/", default='product/no_image.jpeg',
                              help_text='The image to show for this item')
    cropped = ImageRatioField('image', '400x300')
    product = models.ForeignKey(Product)
    name = models.CharField(null = True, blank = True, max_length = 15, default = None,
        help_text = "text to show above image")


class StaffMember(SortableNamedModel):
    email = models.EmailField(null=True, blank=True)
    show_on_contact_us = models.BooleanField(default=False)
    title = models.CharField(null=True, blank=True, max_length=100)


class Address(models.Model):
    street = models.CharField(max_length=100)
    zip = models.CharField(max_length=5)
    city = models.CharField(max_length=100)

    class Meta:
        abstract = True


class Location(ModelWithPicture, Address):
    description = models.TextField(null=True)
    phone_number = models.CharField(null=True, blank=True, max_length=13)
    staff = models.ManyToManyField(StaffMember)
    def address(self):
        return self.street


class LocationPicture(models.Model, ImageTagModel):
    image = models.ImageField(upload_to=upload_image)
    cropped = ImageRatioField('image', '400x300')
    location = models.ForeignKey(Location)

    @property
    def name(self):
        return self.location.name


class Job(SortableNamedModel):
    is_active = models.BooleanField(default=True)


class GalleryItem(SortableNamedModel, ImageTagModel):
    image = models.ImageField(upload_to="gallery/")
    large = ImageRatioField('image', '1440x675')
    preview = ImageRatioField('image', '40x40')

    @property
    def cropped(self):
        return self.preview


class ProjectType(ModelWithPicture):
    description = models.TextField(blank=True, null=True)


class Project(ModelWithPicture):
    type = models.ForeignKey(ProjectType)


class ContentPage(ModelWithPicture):
    homepage_position = models.IntegerField(null=True, blank=True,
                                            help_text="The position (1-3) to be shown on the home page "
                                                      "(under the gallery item display).  If left blank, the page can "
                                                      "still be navigated to, but will not have a section on the "
                                                      "home page.")


class MenuItem(SortableNamedModel):
    parent = models.ForeignKey("MenuItem", null=True, blank=True, help_text="The item to make this a subitem of.")

class Special(SortableNamedModel):
    start_date = models.DateField()
    end_date = models.DateField()
    header_color = models.CharField(null=True, blank=True, max_length=15, default=None)
    

class DeliveryCharge(SortableNamedModel):
    max_milage = models.DecimalField(null = False, blank = False, decimal_places=2, max_digits = 15,
        help_text="The maximum miles allowed for this rate")
    dump_rate = models.DecimalField(null = True, blank = True, decimal_places=2, max_digits = 15,
        help_text = "The price for dump truck delivery")
    flatbed_rate = models.DecimalField(null = True, blank = True, decimal_places=2, max_digits = 15,
        help_text = "The price for flatbed delivery")
    lookup_id = models.CharField(null = False, blank =False, max_length = 15, default = None, 
        help_text = 'Quickbooks Lookup')
    
    class Meta:
        ordering = ['lookup_id']
    

templates/web/category_detail.html
{% extends 'web/content_page.html' %}
{% load staticfiles %}
{% load cropping %}
{% block head_scripts %}
<link href="{% static 'js/jquery.fancybox.css' %}" rel="stylesheet" type="text/css" />

{% endblock %}
{% block header_title %}{{ category.name }}{% endblock %}
{% block image_grid %}
    <div class="grid_4" style="margin-left: 0">
        <div class="box" style="padding:7px;margin:0 1em 0 0; ">
            <a title="{{ category.name }}" href="{{ category.image.url }}" class="fancybox">
                <img src="{% cropped_thumbnail category "cropped" height=220 %}" />
                <div style="text-align:center;margin-top:.3em;"><span class="fa fa-search-plus"> Enlarge</span></div>
            </a>
        </div>
    </div>
{% endblock %}
{% block content_blurb%}
    <strong>{% if category.short_description %} {{ category.short_description | linebreaks }}{% endif %}</strong>
    {{ category.long_description| linebreaks }}
{% endblock %}
{% block main_content %}
{% for category in category.children.all%}
        <div class="grid_3">
            <div class="box">
                <div class="box_title maxheight ta__center"><a href='{% url 'category' category.slug %}'>{{ category.name }}</a></div>
                        <a href="{% url 'category' category.slug %}"><img src="{% cropped_thumbnail category "cropped" height=165  %}" /></a>
                        <div class="box_bot">
                            <div>{% if category.short_description != None %} {{ category.short_description }}{% endif %}</div>
                        </div>
            </div>
        </div>


    {% endfor %}
    {% for product in category.product_set.all%}
        <div class="grid_3">
            <div class="box">
            <div class="maxheight"><div class="boxinner">
                <div class="box_title maxheight2 ta__center">
                    {% if product.short_description %}
                        <a title="{{ product.name }}" href='{% url 'productDetail' product.slug %}'>{{ product.name }}</a>
                    {% else %}
                        <a title="{{ product.name }}" href="{% cropped_thumbnail product "cropped" width=2000 %}" class="fancybox">{{ product.name }}</a>
                    {% endif %}
                </div>
                {% if product.short_description %}
                    <a title="{{ product.name }}" href='{% url 'productDetail' product.slug %}' style="position: relative; display:block; height: 220px;">
                        <img src="{% cropped_thumbnail product "cropped" height=165 %}" />
                        {% if product.sold_out%}
                        <img src="{% static 'images/sold.png' %}" style="position:absolute; top:0; height:165px" />
                        {% endif %}
                    </a>
                {% else %}
                    <a title="{{ product.name }}" href="{% cropped_thumbnail product "cropped" width=2000 %}" class="fancybox" style="position: relative; display:block; height: 220px;">
                        <img src="{% cropped_thumbnail product "cropped" height=165 %}" />
                        {% if product.sold_out%}
                        <img src="{% static 'images/sold.png' %}" style="position:absolute; top:0; height:165px" />
                        {% endif %}
                    </a>
                {% endif %}
                <div class="box_bot ta__center">
                    {% if product.retail_price %}
                        ${{ product.retail_price | stringformat:"1.2f" }}
                    {% endif %}
                </div>
            </div></div>
            </div>
        </div>


    {% endfor %}
     <!-- Preload it -->
    <div style="display: none;">
        <img style="display: none" src="{{ category.image.url }}" />
    {% for product in category.product_set.all%}
       
        <img style="display: none" src="{% cropped_thumbnail product "cropped" width=2000 %}" />
                
    {% endfor %}
    </div>
{% endblock %}
{% block end_scripts %}
    <script src="{% static 'js/jquery.fancybox.js' %}"></script>
    <script type="text/javascript">
        $(function(){
           $('.fancybox').fancybox();
        });
    </script>
{% endblock %}

templates/web/content_page.html
{% extends 'web/base.html' %}
{% load staticfiles %}
{% block head_scripts %}
{% endblock %}
{% block content %}
 <div class="container" style="min-height: 350px">
 <div class="row">
    <div class="grid_12">
    <h2>{% block header_title %}{% endblock %}</h2>
    {% block image_grid %}
    <div class="grid_3" style="margin-left: 0">
        <div class="box" style="padding:7px;margin:0 1em 0 0; ">
            {% block header_graphic %}
            <img src="{% block header_image_src %}{% endblock %}"  style="width:220px;" />
            {% endblock %}
        <!--
            <div class="box_bot">{% block under_header_graphic %}{% endblock %}</div>
        -->
        </div>

    </div>
    {% endblock %}
       {% block content_blurb %}{% endblock %}

 </div>
 </div>
 <div class="row">
    {% block main_content %}{% endblock %}
 </div>
</div>
{% endblock %}

templates/web/job_detail.html
{% extends 'web/content_page.html' %}
{% load staticfiles %}
{% load i18n %}
{% block header_title %}{{ job.name }}{% endblock %}
{% block header_image_src %}{% static 'images/jobs.jpg' %}{% endblock %}
{% block content_blurb %}
 <strong>{{ job.short_description | linebreaks }}</strong>
 {{ job.long_description | linebreaks }}
 <p>
     {% blocktrans %}
     To apply for this job, please send an email with your resume (in word or pdf format) to
     <a href="mailto:jobs@bedrockstoneanddesign.com">jobs@bedrockstoneanddesign.com</a>
     {% endblocktrans %}
 </p>
{% endblock %}

templates/web/job_list.html
{% extends 'web/content_page.html' %}
{% load staticfiles %}
{% load i18n %}
{% block header_title %}Jobs at Bedrock Stone &amp; Design{% endblock %}
{% block header_image_src %}{% static 'images/jobs.jpg' %}{% endblock %}
{% block content_blurb %}
{% if jobs  %}
    <div class="row">
    <ul>
        {% for job in jobs %}
            <li>
                <a href="{% url 'job' job.slug%}">
                <h3>{{job.name  }}</a></h3>
                <strong>
                    {{job.short_description | linebreaks}}
                </strong>
                </a>
                <div>
                <a href="{%url 'job' job.slug %}">more info...</a>
                </div>
            </li>
        {% endfor %}
    </ul>
    </div>

{% else %}
    <p>{% trans "We currently have no openings. Please check back later." %}</p>
{% endif %}
{% endblock %}

templates/web/location.html
{% extends 'web/content_page.html' %}
{% load staticfiles %}
{% load cropping %}
{% load i18n %}
{% block head_scripts %}
<link href="{% static 'js/jquery.fancybox.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block header_title %}{{ location.name }}{% endblock %}
{% block header_graphic %}
    <a href="//maps.google.com?q={{ location.address |iriencode }},{{ location.city }}{{ ' '|iriencode }}{{ location.zip }}" target="google">
        <img src="//maps.googleapis.com/maps/api/staticmap?zoom=14&size=200x200&markers={{ location.address |iriencode }},{{ location.city }}{{ ' '|iriencode }}{{ location.zip }}">
    </a>
    <div class="box_bot">
     <a href="//maps.google.com?q={{ location.address |iriencode }},{{ location.city }}{{ ' '|iriencode }}{{ location.zip }}" target="google">
        <address>
            {{ location.address }}<br />{{location.city }}, TX, {{ location.zip }}
        </address>
     </a>
    <a href="tel:+1{{ location.phone_number }}">{{ location.phone_number }}</a>
    </div>
    </a>
{% endblock %}
{% block content_blurb %}
    <strong>
        {% if location.short_description %}
            {{ location.short_description | linebreaks }}
        {% endif %}
    </strong>
    {{ location.long_description| linebreaks }}
    <h3>Senior Staff</h3>
    <p>
        {% for staffMember in location.staff.all %}
            {{ staffMember.name }} - {{ staffMember.title }} <br />
        {% endfor %}
    </p>

{% endblock %}
{% block main_content %}
<h3>{% blocktrans with location.name as location_name %} A few pictures of {{ location_name }} {% endblocktrans %}</h3>
{% for picture in location.locationpicture_set.all %}
    <div class="grid_3">
            <div class="box">
                <div class="maxheight">
                    <div class="box_inner">
                        <div class="box_title"><div></div></div>
                        <a class="fancybox" href='{% cropped_thumbnail picture 'cropped' width=800 %}'><img src="{% cropped_thumbnail picture "cropped" height=165  %}" /></a>
                        <img src="{% cropped_thumbnail picture 'cropped' width=800 %}" style="display: none;" />  
                        <div class="box_bot">
                            <div></div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
{% endfor %}
{% endblock %}
{% block end_scripts %}
    <script src="{% static 'js/jquery.fancybox.js' %}"></script>
    <script type="text/javascript">
        $(function(){
           $('.fancybox').fancybox();
        });
    </script>
{% endblock %}

templates/web/product_detail.html
{% extends 'web/content_page.html' %}
{% load staticfiles %}
{% load cropping %}

{% load i18n %}
{% block head_scripts %}
<link href="{% static 'js/jquery.fancybox.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}
{% block header_title %}{{ product.name }}{% endblock %}
{% block image_grid %}
    <div class="grid_9" style="margin-left: 0">
        <div class="box" style="padding:7px;margin:0 1em 0 0; ">
            <a title="{{ product.name }}" href="{{ product.image.url }}" class="fancybox">
                <img src="{% cropped_thumbnail product "cropped" width=690 %}" />
                <div style="text-align:center;margin-top:.3em;"><span class="fa fa-search-plus"> Enlarge</span></div>
            </a>
        </div>
    </div>
{% endblock %}
{% block content_blurb %}
 <strong>{{ product.short_description | linebreaks }}</strong>
 {{ product.long_description | safe }}
 {% endblock %}
 {% block main_content %}
   
   {% if product.productimage_set.all %}
   <h3>{{ product.more_images_text }}</h3>
   {% for product_image in product.productimage_set.all %}
   <div class="grid_3">
            <div class="box">
                <div class="maxheight">
                    <div class="boxinner">
                        <div class="box_title">
                            {%if product_image.name %}
                                {{ product_image.name }}
                            {% endif %}
                        </div>
                        <a title="{{ product_image.name }}" href="{% cropped_thumbnail product_image "cropped" width=2000 %}" class="fancybox">
                            <img src="{% cropped_thumbnail product_image "cropped" height=165 %}" />
                        </a>
                        <div class="box_bot"></div>
                    </div>
                </div>
            </div>
    </div>
   {% endfor %}
   {%endif%}
 {% endblock %}
 {% block end_scripts %}
 
    <script src="{% static 'js/jquery.fancybox.js' %}"></script>
    <script type="text/javascript">
        $(function(){
           $('.fancybox').fancybox();
        });
    </script>
    <div style="display:none">
    <!-- PRELOAD -->
    <img src="{% cropped_thumbnail product "cropped" width=2000 %}" />
    {% for product_image in product.productimage_set.all %}
        <img src="{% cropped_thumbnail product_image "cropped" width=2000 %}" />
    {% endfor %}
    </div>
{% endblock %}

templates/web/products_0.html
{% extends 'web/base.html' %}
{% load staticfiles %}
{% block head_scripts %}
{% endblock %}
{% block content %}
 <div class="container">
 <div class="row">
    <div class="grid_12">
    <h3>Products</h3>
    <div class="grid_3">
        <div class="box" style="padding:7px;margin:0 1em 0 0; ">
            <img src="{% static 'images/products.jpg' %}"  style="width:200px;" />
        </div>
    </div>

    <p>
        Bedrock Stone &amp; Design is proud to feature the largest selection of stone products in the Austin, Tx
        area. You can browse just a few of them here.
    </p>
 </div>
 </div>
 <div class="row">
{% for category in categories %}
       <div class="grid_4">
            <div class="box">
                <div class="maxheight" style="height: 460px;">
                    <div class="box_inner">
                        <div class="box_title">{{ category.name }}</div>
                        <img src="{{ MEDIA_URL }}{{ category.image }}" alt="">
                        <div class="box_bot">
                            <div>{{ category.description |linebreaks }}</div>
                            <a href="{% url 'category' category.slug %}" class="btn">View Products</a>
                        </div>

                    </div>
                </div>
            </div>
           <!--
        <a href="full-gallery-2.html" class="lightbox"><img src="{{ MEDIA_URL }}{{ category.image }}" alt=""></a>
        <div class="text1"><a href="#">{{ category.name }}</a></div>
        {{ categories.description }}
        -->
      </div>
{% endfor %}
 </div>
<div class="clear sep__2"></div>
 </div>

{% endblock %}

templates/web/projecttype_detail.html
{% extends 'web/content_page.html' %}
{% load staticfiles %}
{% load cropping %}
{% block head_scripts %}
<link href="{% static 'js/jquery.fancybox.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}
{% block header_title %}{{ projecttype.name }}{% endblock %}
{% block header_image_src %}{% cropped_thumbnail projecttype "cropped" height=165 %}{% endblock %}
{% block content_blurb%}{{ projecttype.description| linebreaks }}{% endblock %}
{% block main_content %}
    {% for product in projecttype.project_set.all%}
        <div class="grid_3">
            <div class="box">
                <div class="box_title"><a title="{{ product.name }}" href="{{ product.image.url }}" class="fancybox">{{ product.name }}</a></div>
                <a title="{{ product.name }}" href="{{ product.image.url }}" class="fancybox">
                <img src="{% cropped_thumbnail product "cropped" height=165 %}" />
                </a>
                <img style="display: none" src="{{ product.image.url }}" />
                <div class="box_bot">
                            <div></div>
                        </div>
            </div>
        </div>


    {% endfor %}
     
    </div>
{% endblock %}
{% block end_scripts %}
    <script src="{% static 'js/jquery.fancybox.js' %}"></script>
    <script type="text/javascript">
        $(function(){
           $('.fancybox').fancybox();
        });
    </script>
{% endblock %}

templates/web/sales_lead.html
{% extends 'web/content_page.html' %}
{% load staticfiles %}
{% load i18n %}
{% block header_title %}{% trans "Contact Us" %}{% endblock %}
{% block head_scripts %}
<link href="{% static 'js/jquery.fancybox.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'css/form.css' %}" rel="stylesheet" type="text/css" />
<style type="text/css">
    #form label label{
        font-size: 15px;
        min-height: 25px;
        font-weight: bold;
        margin-top:.2em;
    }
</style>
{% endblock %}
{% block image_grid %}{% endblock %}
{% block content_blurb %}
    {% blocktrans %}
        Please fill out the form below, and one of our sales representatives will contact 
        you shortly.
    {% endblocktrans %}
    <br />
    <form method="POST" id="form">
        {% csrf_token %} 
            <label>
                <label class="message" for="name">Full Name:</label>
                <input id="name" name="name" placeholder="Full Name" required="required" />
            </label>
            <label>
                <label for="emailAddress">Email Address:</label>
                <input id="emailAddress" name="emailAddress" placeholder="Email Address" required="required" type="email" />
            </label>
            <label>
                <label for="phoneNumber">Phone Number:</label>
                <input id="phoneNumber" name="phoneNumber" placeholder="Phone Number" />
            </label>
            <label>
                <label for="info">Info about your project:</label>
                <textarea id="info" name="Information"></textarea>
            </label>
            <label class="btns">
                <button type="submit" value="OK" class="btn">Submit</button>
            </label>
    </form>
{% endblock %}

templates/web/services.html
{% extends 'web/content_page.html' %}
{% load staticfiles %}
{% block header_title %}Services{% endblock %}
{% block header_image_src %}{% static 'images/delivery.jpg' %}{% endblock %}
{% block content_blurb %}
<p>
    24 hour shipping includes Greater Austin and surrounding cities, San Antonio, Lake Travis, Dripping Springs,
    Greater Marble Falls, George Town etc. Call to confirm your city. We will usually get it there the same day
    or within 24 hours!
</p>

{% endblock %}

templates/web/simple-slider.source.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Simple Slider Example - Jssor Slider, Slideshow</title>
</head>
<body style="font-family:Arial, Verdana;background-color:#fff;">
    <!-- it works the same with all jquery version from 1.x to 2.x -->
    <script type="text/javascript" src="../js/jquery-1.9.1.min.js"></script>
    <!-- use jssor.slider.mini.js (39KB) or jssor.sliderc.mini.js (31KB, with caption, no slideshow) or jssor.sliders.mini.js (26KB, no caption, no slideshow) instead for release -->
    <!-- jssor.slider.mini.js = jssor.sliderc.mini.js = jssor.sliders.mini.js = (jssor.core.js + jssor.utils.js + jssor.slider.js) -->
    <script type="text/javascript" src="../js/jssor.core.js"></script>
    <script type="text/javascript" src="../js/jssor.utils.js"></script>
    <script type="text/javascript" src="../js/jssor.slider.js"></script>
    <script>

        jQuery(document).ready(function ($) {
            var options = {

                $AutoPlay: true,                                   //[Optional] Whether to auto play, to enable slideshow, this option must be set to true, default value is false
                $DragOrientation: 3                                //[Optional] Orientation to drag slide, 0 no drag, 1 horizental, 2 vertical, 3 either, default value is 1 (Note that the $DragOrientation should be the same as $PlayOrientation when $DisplayPieces is greater than 1, or parking position is not 0)
            };

            var jssor_slider1 = new $JssorSlider$("slider1_container", options);
        });
    </script>
    <div id="slider1_container" style="position: relative; top: 0px; left: 0px; width: 600px;
        height: 300px;">
        <!-- Slides Container -->
        <div u="slides" style="cursor: move; position: absolute; left: 0px; top: 0px; width: 600px; height: 300px;
            overflow: hidden;">
            <div><img u="image" src="../img/landscape/01.jpg" /></div>
            <div><img u="image" src="../img/landscape/02.jpg" /></div>
            <div><img u="image" src="../img/landscape/03.jpg" /></div>
            <div><img u="image" src="../img/landscape/04.jpg" /></div>
            <div><img u="image" src="../img/landscape/05.jpg" /></div>
            <div><img u="image" src="../img/landscape/06.jpg" /></div>
            <div><img u="image" src="../img/landscape/07.jpg" /></div>
            <div><img u="image" src="../img/landscape/08.jpg" /></div>
        </div>
        <a style="display: none" href="http://www.jssor.com">html slideshow</a>
    </div>
</body>
</html>

templates/web/specials.html
{% extends 'web/content_page.html' %}
{% load staticfiles %}
{% load cropping %}
{% block head_scripts %}
<style type="text/css">
  .special{
    border: dashed 4px black;
    margin: 1rem;
    padding: 1rem;
    background: white;
    width: 80%;
    text-align: center;
    font-size:xx-large;
  }
  .special:hover{
    border: dashed 4px #2dabdf;
    cursor: pointer;
  }
  .special h3{
    color: #5ab645;
    font-size: 75px;
    margin-bottom: .5em;
    line-height: 55px;
  }
  .special strong{
    line-height: 30px;
  }
  .special .pink{
    color: deeppink;
  }
  .special p{
    font-size: large;
    margin-top:.5em;
  }
  .special span a{
    font-size: medium;
    margin-top:1em;
  }
  .special .valid_through{
    border:solid 1px black;
    width: 45%;
    font-size: small;
    margin: 0 auto;
    text-align: center;
    text-transform: uppercase;
  }
</style>
{% endblock %}
{% block content %}
  <div class="container" style="min-height: 350px">
    <div class="row">
      <div class="grid_12" >
        <h2>Bedrock Specials</h2>
        {% for special in specials %}
        <div class='special' onclick="window.location='{{special.slug}}'">
          {% if special.header_color %}
          <h3 style="color: {{ special.header_color }}">{{ special.name }}</h3>
          {% else %}
          <h3>{{ special.name }}</h3>
          {% endif %}
          <strong>{{special.short_description}}</strong>
          <br />
          <p>
           {{special.long_description}}
          </p>
          <div class="valid_through">
            Coupon valid at time of purchase.<br />
            Offer valid through {{special.end_date}}
          </div>
          
        </div>
        {% endfor %}
        
        </div>
      </div>
    </div>
  </div>
{% endblock %}